# Generated by Django 2.0.7 on 2018-08-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_auto_20180818_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ('model',)},
        ),
    ]
