# Generated by Django 2.0.7 on 2018-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_auto_20180822_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='additional_equipment',
            field=models.ManyToManyField(related_name='drones', to='drone.AditionalEquipment'),
        ),
    ]
